// Thematic vocabulary packs to broaden Michelle from a conversational core
// toward high-school breadth (Spanish 1-4 / CEFR A1-B1). Words are neutral Latin
// American / Ecuadorian. Each pack can be browsed, heard, and sent into spaced
// repetition. Adding a pack or a word is just editing this list.

export interface VocabWord {
  es: string
  en: string
  pos?: string
}

export interface VocabPack {
  id: string
  title: string
  level: 'A1' | 'A2' | 'B1'
  words: VocabWord[]
}

export const vocabPacks: VocabPack[] = [
  {
    id: 'familia-ext',
    title: 'La familia',
    level: 'A1',
    words: [
      { es: 'el esposo', en: 'husband' },
      { es: 'la esposa', en: 'wife' },
      { es: 'el hijo', en: 'son' },
      { es: 'la hija', en: 'daughter' },
      { es: 'el tío', en: 'uncle' },
      { es: 'la tía', en: 'aunt' },
      { es: 'el primo', en: 'cousin (m)' },
      { es: 'la prima', en: 'cousin (f)' },
      { es: 'el sobrino', en: 'nephew' },
      { es: 'la sobrina', en: 'niece' },
      { es: 'el nieto', en: 'grandson' },
      { es: 'la nieta', en: 'granddaughter' },
      { es: 'el suegro', en: 'father-in-law' },
      { es: 'la suegra', en: 'mother-in-law' },
      { es: 'el cuñado', en: 'brother-in-law' },
      { es: 'el padrino', en: 'godfather' },
      { es: 'la madrina', en: 'godmother' },
      { es: 'el bebé', en: 'baby' },
      { es: 'los parientes', en: 'relatives' },
      { es: 'los gemelos', en: 'twins' },
    ],
  },
  {
    id: 'escuela',
    title: 'La escuela y las clases',
    level: 'A1',
    words: [
      { es: 'la escuela', en: 'school' },
      { es: 'el colegio', en: 'high school' },
      { es: 'la universidad', en: 'university' },
      { es: 'el profesor', en: 'teacher (m)' },
      { es: 'la profesora', en: 'teacher (f)' },
      { es: 'el estudiante', en: 'student' },
      { es: 'la clase', en: 'class' },
      { es: 'la materia', en: 'subject' },
      { es: 'las matemáticas', en: 'math' },
      { es: 'la historia', en: 'history' },
      { es: 'la ciencia', en: 'science' },
      { es: 'el idioma', en: 'language' },
      { es: 'el examen', en: 'exam' },
      { es: 'la tarea', en: 'homework' },
      { es: 'la nota', en: 'grade' },
      { es: 'el horario', en: 'schedule' },
      { es: 'la biblioteca', en: 'library' },
      { es: 'el cuaderno', en: 'notebook' },
      { es: 'la mochila', en: 'backpack' },
      { es: 'aprender', en: 'to learn', pos: 'v.' },
      { es: 'enseñar', en: 'to teach', pos: 'v.' },
      { es: 'estudiar', en: 'to study', pos: 'v.' },
    ],
  },
  {
    id: 'rutina',
    title: 'La rutina diaria',
    level: 'A2',
    words: [
      { es: 'despertarse', en: 'to wake up', pos: 'v.' },
      { es: 'levantarse', en: 'to get up', pos: 'v.' },
      { es: 'ducharse', en: 'to shower', pos: 'v.' },
      { es: 'bañarse', en: 'to bathe', pos: 'v.' },
      { es: 'vestirse', en: 'to get dressed', pos: 'v.' },
      { es: 'cepillarse los dientes', en: 'to brush your teeth', pos: 'v.' },
      { es: 'peinarse', en: 'to comb your hair', pos: 'v.' },
      { es: 'lavarse', en: 'to wash up', pos: 'v.' },
      { es: 'afeitarse', en: 'to shave', pos: 'v.' },
      { es: 'desayunar', en: 'to have breakfast', pos: 'v.' },
      { es: 'almorzar', en: 'to have lunch', pos: 'v.' },
      { es: 'cenar', en: 'to have dinner', pos: 'v.' },
      { es: 'trabajar', en: 'to work', pos: 'v.' },
      { es: 'descansar', en: 'to rest', pos: 'v.' },
      { es: 'acostarse', en: 'to go to bed', pos: 'v.' },
      { es: 'dormirse', en: 'to fall asleep', pos: 'v.' },
      { es: 'temprano', en: 'early', pos: 'adv.' },
      { es: 'tarde', en: 'late', pos: 'adv.' },
    ],
  },
  {
    id: 'casa',
    title: 'La casa',
    level: 'A1',
    words: [
      { es: 'la cocina', en: 'kitchen' },
      { es: 'la sala', en: 'living room' },
      { es: 'el dormitorio', en: 'bedroom' },
      { es: 'el baño', en: 'bathroom' },
      { es: 'el comedor', en: 'dining room' },
      { es: 'la cama', en: 'bed' },
      { es: 'la silla', en: 'chair' },
      { es: 'el sofá', en: 'couch' },
      { es: 'la puerta', en: 'door' },
      { es: 'la ventana', en: 'window' },
      { es: 'el refrigerador', en: 'fridge' },
      { es: 'la estufa', en: 'stove' },
      { es: 'la ducha', en: 'shower' },
      { es: 'el espejo', en: 'mirror' },
      { es: 'la lámpara', en: 'lamp' },
      { es: 'el piso', en: 'floor' },
      { es: 'la pared', en: 'wall' },
      { es: 'el jardín', en: 'garden / yard' },
      { es: 'las llaves', en: 'keys' },
      { es: 'el mueble', en: 'piece of furniture' },
    ],
  },
  {
    id: 'comida',
    title: 'La comida y la bebida',
    level: 'A1',
    words: [
      { es: 'el huevo', en: 'egg' },
      { es: 'la leche', en: 'milk' },
      { es: 'el queso', en: 'cheese' },
      { es: 'la fruta', en: 'fruit' },
      { es: 'la manzana', en: 'apple' },
      { es: 'el plátano', en: 'banana / plantain' },
      { es: 'la naranja', en: 'orange' },
      { es: 'el frejol', en: 'bean' },
      { es: 'la papa', en: 'potato' },
      { es: 'el pescado', en: 'fish (food)' },
      { es: 'la verdura', en: 'vegetable' },
      { es: 'la ensalada', en: 'salad' },
      { es: 'el postre', en: 'dessert' },
      { es: 'el azúcar', en: 'sugar' },
      { es: 'el aceite', en: 'oil' },
      { es: 'el pan', en: 'bread' },
      { es: 'la mantequilla', en: 'butter' },
      { es: 'la cerveza', en: 'beer' },
      { es: 'el vino', en: 'wine' },
      { es: 'rico', en: 'tasty', pos: 'adj.' },
    ],
  },
  {
    id: 'cuerpo-salud',
    title: 'El cuerpo y la salud',
    level: 'A2',
    words: [
      { es: 'la cabeza', en: 'head' },
      { es: 'el ojo', en: 'eye' },
      { es: 'la nariz', en: 'nose' },
      { es: 'la boca', en: 'mouth' },
      { es: 'la oreja', en: 'ear' },
      { es: 'el diente', en: 'tooth' },
      { es: 'el cuello', en: 'neck' },
      { es: 'el brazo', en: 'arm' },
      { es: 'la mano', en: 'hand' },
      { es: 'el dedo', en: 'finger' },
      { es: 'la pierna', en: 'leg' },
      { es: 'el pie', en: 'foot' },
      { es: 'el corazón', en: 'heart' },
      { es: 'la espalda', en: 'back' },
      { es: 'enfermo', en: 'sick', pos: 'adj.' },
      { es: 'sano', en: 'healthy', pos: 'adj.' },
      { es: 'la fiebre', en: 'fever' },
      { es: 'la gripe', en: 'the flu' },
      { es: 'la tos', en: 'cough' },
      { es: 'el médico', en: 'doctor' },
    ],
  },
  {
    id: 'ropa-colores',
    title: 'La ropa y los colores',
    level: 'A1',
    words: [
      { es: 'la camisa', en: 'shirt' },
      { es: 'el pantalón', en: 'pants' },
      { es: 'los zapatos', en: 'shoes' },
      { es: 'el vestido', en: 'dress' },
      { es: 'la falda', en: 'skirt' },
      { es: 'la chaqueta', en: 'jacket' },
      { es: 'el abrigo', en: 'coat' },
      { es: 'las medias', en: 'socks' },
      { es: 'la gorra', en: 'cap' },
      { es: 'rojo', en: 'red', pos: 'adj.' },
      { es: 'azul', en: 'blue', pos: 'adj.' },
      { es: 'verde', en: 'green', pos: 'adj.' },
      { es: 'amarillo', en: 'yellow', pos: 'adj.' },
      { es: 'negro', en: 'black', pos: 'adj.' },
      { es: 'blanco', en: 'white', pos: 'adj.' },
      { es: 'gris', en: 'gray', pos: 'adj.' },
      { es: 'café', en: 'brown', pos: 'adj.' },
      { es: 'morado', en: 'purple', pos: 'adj.' },
      { es: 'rosado', en: 'pink', pos: 'adj.' },
      { es: 'anaranjado', en: 'orange', pos: 'adj.' },
    ],
  },
  {
    id: 'pasatiempos',
    title: 'Pasatiempos y deportes',
    level: 'A2',
    words: [
      { es: 'el fútbol', en: 'soccer' },
      { es: 'el básquet', en: 'basketball' },
      { es: 'nadar', en: 'to swim', pos: 'v.' },
      { es: 'correr', en: 'to run', pos: 'v.' },
      { es: 'bailar', en: 'to dance', pos: 'v.' },
      { es: 'cantar', en: 'to sing', pos: 'v.' },
      { es: 'leer', en: 'to read', pos: 'v.' },
      { es: 'escribir', en: 'to write', pos: 'v.' },
      { es: 'dibujar', en: 'to draw', pos: 'v.' },
      { es: 'jugar', en: 'to play', pos: 'v.' },
      { es: 'la música', en: 'music' },
      { es: 'la película', en: 'movie' },
      { es: 'el videojuego', en: 'video game' },
      { es: 'caminar', en: 'to walk', pos: 'v.' },
      { es: 'el ejercicio', en: 'exercise' },
      { es: 'el equipo', en: 'team' },
      { es: 'ganar', en: 'to win', pos: 'v.' },
      { es: 'perder', en: 'to lose', pos: 'v.' },
    ],
  },
  {
    id: 'profesiones',
    title: 'Las profesiones',
    level: 'A2',
    words: [
      { es: 'el ingeniero', en: 'engineer' },
      { es: 'el abogado', en: 'lawyer' },
      { es: 'el enfermero', en: 'nurse' },
      { es: 'el policía', en: 'police officer' },
      { es: 'el bombero', en: 'firefighter' },
      { es: 'el cocinero', en: 'cook' },
      { es: 'el mesero', en: 'waiter' },
      { es: 'el conductor', en: 'driver' },
      { es: 'el vendedor', en: 'salesperson' },
      { es: 'el agricultor', en: 'farmer' },
      { es: 'el contador', en: 'accountant' },
      { es: 'el dentista', en: 'dentist' },
      { es: 'el artista', en: 'artist' },
      { es: 'el escritor', en: 'writer' },
      { es: 'el jefe', en: 'boss' },
      { es: 'el cliente', en: 'customer' },
      { es: 'el dueño', en: 'owner' },
      { es: 'el trabajo', en: 'job / work' },
    ],
  },
  {
    id: 'ciudad',
    title: 'La ciudad y los lugares',
    level: 'A2',
    words: [
      { es: 'la iglesia', en: 'church' },
      { es: 'el supermercado', en: 'supermarket' },
      { es: 'el cine', en: 'movie theater' },
      { es: 'el museo', en: 'museum' },
      { es: 'la plaza', en: 'square / plaza' },
      { es: 'la calle', en: 'street' },
      { es: 'la avenida', en: 'avenue' },
      { es: 'el aeropuerto', en: 'airport' },
      { es: 'la parada', en: 'bus stop' },
      { es: 'el barrio', en: 'neighborhood' },
      { es: 'el semáforo', en: 'traffic light' },
      { es: 'el puente', en: 'bridge' },
      { es: 'el edificio', en: 'building' },
      { es: 'la tienda', en: 'shop' },
      { es: 'el correo', en: 'post office' },
      { es: 'la gasolinera', en: 'gas station' },
      { es: 'el estadio', en: 'stadium' },
      { es: 'la cuadra', en: 'block' },
    ],
  },
  {
    id: 'tecnologia',
    title: 'La tecnología',
    level: 'A2',
    words: [
      { es: 'la computadora', en: 'computer' },
      { es: 'el celular', en: 'cell phone' },
      { es: 'el internet', en: 'internet' },
      { es: 'la pantalla', en: 'screen' },
      { es: 'el teclado', en: 'keyboard' },
      { es: 'el correo', en: 'email' },
      { es: 'el mensaje', en: 'message' },
      { es: 'la aplicación', en: 'app' },
      { es: 'la contraseña', en: 'password' },
      { es: 'la red social', en: 'social network' },
      { es: 'el cargador', en: 'charger' },
      { es: 'la batería', en: 'battery' },
      { es: 'descargar', en: 'to download', pos: 'v.' },
      { es: 'subir', en: 'to upload', pos: 'v.' },
      { es: 'prender', en: 'to turn on', pos: 'v.' },
      { es: 'apagar', en: 'to turn off', pos: 'v.' },
      { es: 'la foto', en: 'photo' },
      { es: 'el video', en: 'video' },
    ],
  },
  {
    id: 'naturaleza',
    title: 'La naturaleza y el medio ambiente',
    level: 'B1',
    words: [
      { es: 'el árbol', en: 'tree' },
      { es: 'la flor', en: 'flower' },
      { es: 'la planta', en: 'plant' },
      { es: 'el río', en: 'river' },
      { es: 'el mar', en: 'sea' },
      { es: 'la montaña', en: 'mountain' },
      { es: 'la playa', en: 'beach' },
      { es: 'el bosque', en: 'forest' },
      { es: 'el cielo', en: 'sky' },
      { es: 'el sol', en: 'sun' },
      { es: 'la luna', en: 'moon' },
      { es: 'la estrella', en: 'star' },
      { es: 'el animal', en: 'animal' },
      { es: 'el pájaro', en: 'bird' },
      { es: 'la basura', en: 'trash' },
      { es: 'reciclar', en: 'to recycle', pos: 'v.' },
      { es: 'contaminar', en: 'to pollute', pos: 'v.' },
      { es: 'el medio ambiente', en: 'the environment' },
      { es: 'cuidar', en: 'to take care of', pos: 'v.' },
      { es: 'la naturaleza', en: 'nature' },
    ],
  },
  {
    id: 'descripciones',
    title: 'Describir personas',
    level: 'A2',
    words: [
      { es: 'alto', en: 'tall', pos: 'adj.' },
      { es: 'bajo', en: 'short', pos: 'adj.' },
      { es: 'delgado', en: 'thin', pos: 'adj.' },
      { es: 'joven', en: 'young', pos: 'adj.' },
      { es: 'viejo', en: 'old', pos: 'adj.' },
      { es: 'guapo', en: 'handsome', pos: 'adj.' },
      { es: 'bonito', en: 'pretty', pos: 'adj.' },
      { es: 'simpático', en: 'nice / friendly', pos: 'adj.' },
      { es: 'amable', en: 'kind', pos: 'adj.' },
      { es: 'inteligente', en: 'intelligent', pos: 'adj.' },
      { es: 'gracioso', en: 'funny', pos: 'adj.' },
      { es: 'serio', en: 'serious', pos: 'adj.' },
      { es: 'tímido', en: 'shy', pos: 'adj.' },
      { es: 'trabajador', en: 'hardworking', pos: 'adj.' },
      { es: 'perezoso', en: 'lazy', pos: 'adj.' },
      { es: 'fuerte', en: 'strong', pos: 'adj.' },
      { es: 'el pelo', en: 'hair' },
      { es: 'los ojos', en: 'eyes' },
    ],
  },
  {
    id: 'emociones',
    title: 'Emociones y sentimientos',
    level: 'A2',
    words: [
      { es: 'feliz', en: 'happy', pos: 'adj.' },
      { es: 'contento', en: 'glad', pos: 'adj.' },
      { es: 'triste', en: 'sad', pos: 'adj.' },
      { es: 'enojado', en: 'angry', pos: 'adj.' },
      { es: 'cansado', en: 'tired', pos: 'adj.' },
      { es: 'aburrido', en: 'bored', pos: 'adj.' },
      { es: 'emocionado', en: 'excited', pos: 'adj.' },
      { es: 'nervioso', en: 'nervous', pos: 'adj.' },
      { es: 'preocupado', en: 'worried', pos: 'adj.' },
      { es: 'asustado', en: 'scared', pos: 'adj.' },
      { es: 'orgulloso', en: 'proud', pos: 'adj.' },
      { es: 'tranquilo', en: 'calm', pos: 'adj.' },
      { es: 'enamorado', en: 'in love', pos: 'adj.' },
      { es: 'el miedo', en: 'fear' },
      { es: 'la alegría', en: 'joy' },
      { es: 'reír', en: 'to laugh', pos: 'v.' },
      { es: 'llorar', en: 'to cry', pos: 'v.' },
      { es: 'sentir', en: 'to feel', pos: 'v.' },
    ],
  },
  {
    id: 'tiempo-calendario',
    title: 'El tiempo y el calendario',
    level: 'A1',
    words: [
      { es: 'lunes', en: 'Monday' },
      { es: 'martes', en: 'Tuesday' },
      { es: 'miércoles', en: 'Wednesday' },
      { es: 'jueves', en: 'Thursday' },
      { es: 'viernes', en: 'Friday' },
      { es: 'sábado', en: 'Saturday' },
      { es: 'domingo', en: 'Sunday' },
      { es: 'el día', en: 'day' },
      { es: 'la semana', en: 'week' },
      { es: 'el mes', en: 'month' },
      { es: 'el año', en: 'year' },
      { es: 'hoy', en: 'today', pos: 'adv.' },
      { es: 'mañana', en: 'tomorrow', pos: 'adv.' },
      { es: 'ayer', en: 'yesterday', pos: 'adv.' },
      { es: 'el fin de semana', en: 'weekend' },
      { es: 'antes', en: 'before', pos: 'adv.' },
      { es: 'después', en: 'after', pos: 'adv.' },
      { es: 'siempre', en: 'always', pos: 'adv.' },
      { es: 'nunca', en: 'never', pos: 'adv.' },
      { es: 'a veces', en: 'sometimes', pos: 'adv.' },
    ],
  },
  {
    id: 'numeros',
    title: 'Los números',
    level: 'A1',
    words: [
      { es: 'cero', en: 'zero' },
      { es: 'uno', en: 'one' },
      { es: 'dos', en: 'two' },
      { es: 'tres', en: 'three' },
      { es: 'cuatro', en: 'four' },
      { es: 'cinco', en: 'five' },
      { es: 'seis', en: 'six' },
      { es: 'siete', en: 'seven' },
      { es: 'ocho', en: 'eight' },
      { es: 'nueve', en: 'nine' },
      { es: 'diez', en: 'ten' },
      { es: 'once', en: 'eleven' },
      { es: 'doce', en: 'twelve' },
      { es: 'quince', en: 'fifteen' },
      { es: 'veinte', en: 'twenty' },
      { es: 'treinta', en: 'thirty' },
      { es: 'cincuenta', en: 'fifty' },
      { es: 'cien', en: 'one hundred' },
      { es: 'mil', en: 'one thousand' },
      { es: 'primero', en: 'first' },
      { es: 'segundo', en: 'second' },
      { es: 'último', en: 'last' },
    ],
  },
  {
    id: 'verbos-comunes',
    title: 'Verbos comunes',
    level: 'A2',
    words: [
      { es: 'hablar', en: 'to speak', pos: 'v.' },
      { es: 'comer', en: 'to eat', pos: 'v.' },
      { es: 'beber', en: 'to drink', pos: 'v.' },
      { es: 'ver', en: 'to see', pos: 'v.' },
      { es: 'dar', en: 'to give', pos: 'v.' },
      { es: 'saber', en: 'to know (facts)', pos: 'v.' },
      { es: 'conocer', en: 'to know (people/places)', pos: 'v.' },
      { es: 'poner', en: 'to put', pos: 'v.' },
      { es: 'salir', en: 'to leave / go out', pos: 'v.' },
      { es: 'llegar', en: 'to arrive', pos: 'v.' },
      { es: 'llevar', en: 'to carry / take', pos: 'v.' },
      { es: 'traer', en: 'to bring', pos: 'v.' },
      { es: 'dejar', en: 'to leave (behind) / let', pos: 'v.' },
      { es: 'encontrar', en: 'to find', pos: 'v.' },
      { es: 'buscar', en: 'to look for', pos: 'v.' },
      { es: 'usar', en: 'to use', pos: 'v.' },
      { es: 'necesitar', en: 'to need', pos: 'v.' },
      { es: 'pensar', en: 'to think', pos: 'v.' },
      { es: 'sentir', en: 'to feel', pos: 'v.' },
      { es: 'creer', en: 'to believe', pos: 'v.' },
    ],
  },
  {
    id: 'transporte-viajes',
    title: 'Transporte y viajes',
    level: 'A2',
    words: [
      { es: 'el avión', en: 'airplane' },
      { es: 'el tren', en: 'train' },
      { es: 'el boleto', en: 'ticket' },
      { es: 'la maleta', en: 'suitcase' },
      { es: 'el pasaporte', en: 'passport' },
      { es: 'el vuelo', en: 'flight' },
      { es: 'la llegada', en: 'arrival' },
      { es: 'la salida', en: 'departure / exit' },
      { es: 'el equipaje', en: 'luggage' },
      { es: 'la aduana', en: 'customs' },
      { es: 'el turista', en: 'tourist' },
      { es: 'el mapa', en: 'map' },
      { es: 'la cámara', en: 'camera' },
      { es: 'la reserva', en: 'reservation' },
      { es: 'el carro', en: 'car' },
      { es: 'manejar', en: 'to drive', pos: 'v.' },
      { es: 'viajar', en: 'to travel', pos: 'v.' },
      { es: 'la frontera', en: 'border' },
    ],
  },
  {
    id: 'conectores',
    title: 'Preguntas y conectores',
    level: 'A2',
    words: [
      { es: 'qué', en: 'what' },
      { es: 'quién', en: 'who' },
      { es: 'cuándo', en: 'when' },
      { es: 'dónde', en: 'where' },
      { es: 'por qué', en: 'why' },
      { es: 'cómo', en: 'how' },
      { es: 'cuánto', en: 'how much' },
      { es: 'cuál', en: 'which' },
      { es: 'porque', en: 'because', pos: 'conj.' },
      { es: 'pero', en: 'but', pos: 'conj.' },
      { es: 'también', en: 'also', pos: 'adv.' },
      { es: 'entonces', en: 'so / then', pos: 'adv.' },
      { es: 'además', en: 'besides / also', pos: 'adv.' },
      { es: 'aunque', en: 'although', pos: 'conj.' },
      { es: 'mientras', en: 'while', pos: 'conj.' },
      { es: 'sin embargo', en: 'however' },
      { es: 'por eso', en: 'that\'s why' },
      { es: 'así que', en: 'so / therefore' },
      { es: 'luego', en: 'later / then', pos: 'adv.' },
      { es: 'por fin', en: 'finally' },
    ],
  },
]

export function totalVocabWords(): number {
  return vocabPacks.reduce((n, p) => n + p.words.length, 0)
}
